// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6fvpOImHEPs7qtlCTOMqLRmGMtUiNAG8',
    appId: '1:863469752891:web:15a5e7b47d862cab4c021e',
    messagingSenderId: '863469752891',
    projectId: 'dashboard-jeve',
    authDomain: 'dashboard-jeve.firebaseapp.com',
    storageBucket: 'dashboard-jeve.appspot.com',
    measurementId: 'G-55P6RY3N9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_LNbDjlR4MMp9EzMB4If3OfCeaLz8miQ',
    appId: '1:863469752891:android:7e87926b6966065c4c021e',
    messagingSenderId: '863469752891',
    projectId: 'dashboard-jeve',
    storageBucket: 'dashboard-jeve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAenLKaH8HJsz-SLlheOiGFwviNzAxUfcM',
    appId: '1:863469752891:ios:f464b2b899a343234c021e',
    messagingSenderId: '863469752891',
    projectId: 'dashboard-jeve',
    storageBucket: 'dashboard-jeve.appspot.com',
    iosClientId: '863469752891-46hsm16pp29bo7s3k2v0tp4v5f4ri7r8.apps.googleusercontent.com',
    iosBundleId: 'it.jeve.dashboard',
  );
}
